server:
  port: 8084

spring:
  application:
    name: commentservice

  datasource:
    url: jdbc:postgresql://192.168.0.7:5432/commentserviceDB
    username: commentservice
    password: commentservice

  jpa:
    properties:
      hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update # Controls database schema generation
    show-sql: true # Shows SQL queries in the logs 192.168.128.3

