FROM openjdk:17-jdk-slim AS build

COPY pom.xml mvnw ./
COPY .mvn .mvn

# clean up the file
RUN sed -i 's/\r$//' mvnw
# run with the SH path
RUN /bin/sh mvnw dependency:resolve

COPY src src
RUN ./mvnw package

FROM openjdk:17-jdk-slim

EXPOSE 8081

WORKDIR /demo

COPY --from=build target/*.jar demo.jar

ENTRYPOINT ["java", "-jar", "demo.jar"]